"""Reusable CLI style and interaction helpers."""

from .tui import create_choice, get_separator
from .input import add_interactive_option
from .core import (
    BACK_VALUE,
    CHECKBOX_SELECTED_INDICATOR,
    CHECKBOX_UNSELECTED_INDICATOR,
    FORCE_INTERACTIVE_NO_TTY_MESSAGE,
    INTERACTIVE_OPTION_HELP,
    MISSING_REQUIRED_NO_TTY_MESSAGE,
)
from .core import abort_if_force_without_tty, abort_if_missing_without_tty
from .render import (
    render_commands,
    render_config_priority,
    render_config_sources,
    render_dry_run,
    render_failure,
    render_flow_start,
    render_plan,
    render_progress_step,
    render_skip,
    render_stage,
    render_success,
    render_warning,
)
from .core import (
    AUTO_PROMPT_ENV_VAR,
    InteractiveResolution,
    auto_prompt_enabled,
    is_interactive_available,
    normalize_interactive,
    resolve_interactive_mode,
)
from .security import format_current_secret, mask_secret, prompt_sensitive_value
from .render import (
    TableColumn,
    get_style,
    render_error,
    render_error_block,
    render_heading,
    render_info,
    render_key_values,
    render_list,
    render_note,
    render_priority_chain,
    render_progress,
    render_section,
    render_status,
    render_step,
    render_suggested_commands,
    render_summary,
    render_table,
)
from .patterns import (
    prompt_sensitive_value_with_mask,
    prompt_text_value,
    resolve_value,
)
from .tui import (
    ask_checkbox,
    ask_checkbox_with_controls,
    ask_confirm,
    ask_path,
    ask_select,
    ask_text,
)
from .input import resolve_command_inputs
from .input import CommandConstraint, CommandField, CommandSchema

__all__ = [
    "AUTO_PROMPT_ENV_VAR",
    "BACK_VALUE",
    "CHECKBOX_SELECTED_INDICATOR",
    "CHECKBOX_UNSELECTED_INDICATOR",
    "CommandConstraint",
    "CommandField",
    "CommandSchema",
    "FORCE_INTERACTIVE_NO_TTY_MESSAGE",
    "INTERACTIVE_OPTION_HELP",
    "InteractiveResolution",
    "MISSING_REQUIRED_NO_TTY_MESSAGE",
    "TableColumn",
    "add_interactive_option",
    "abort_if_force_without_tty",
    "abort_if_missing_without_tty",
    "auto_prompt_enabled",
    "ask_checkbox",
    "ask_checkbox_with_controls",
    "ask_confirm",
    "ask_path",
    "ask_select",
    "ask_text",
    "create_choice",
    "format_current_secret",
    "get_separator",
    "get_style",
    "is_interactive_available",
    "mask_secret",
    "normalize_interactive",
    "prompt_sensitive_value",
    "prompt_sensitive_value_with_mask",
    "prompt_text_value",
    "render_commands",
    "render_config_priority",
    "render_config_sources",
    "render_dry_run",
    "render_error",
    "render_error_block",
    "render_failure",
    "render_flow_start",
    "render_heading",
    "render_info",
    "render_key_values",
    "render_list",
    "render_note",
    "render_plan",
    "render_priority_chain",
    "render_progress",
    "render_progress_step",
    "render_section",
    "render_skip",
    "render_stage",
    "render_status",
    "render_step",
    "render_success",
    "render_suggested_commands",
    "render_summary",
    "render_table",
    "render_warning",
    "resolve_command_inputs",
    "resolve_interactive_mode",
    "resolve_value",
    "__version__",
]

__version__ = "0.1.1"
